// Interakcija sa API-jem na ovaj nacin jer je browser limitiran
GET http://localhost:5165/games

###
GET http://localhost:5165/games/3

###
POST http://localhost:5165/games
Content-Type: application/json

{
    "name": "Candy Crush",
    "tagId": 5,
    "price": 10.99,
    "releaseDate": "2004-07-02",
    "description": "Defeat the vile stones that have corrupted your land",
    "studio": "Gameforge"
}

###
PUT http://localhost:5165/games/3
Content-Type: application/json

{
    "name": "New world",
    "tagId": 1,
    "price": 19.99,
    "releaseDate": "2007-05-15",
    "description": "Fight the evil mastermind to stop him from gaining world control!",
    "studio": "Naughty dog"
}

###
DELETE http://localhost:5165/games/5